version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC alıcısı
      - "4318:4318" # OTLP HTTP alıcısı
      - "8889:8889" # Prometheus metrik çıkışı
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo-local.yaml" ]
    ports:
      - "3200:3200"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - prometheus
      - tempo
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge